---
title: "Client Email Guide"
---

Welcome to PST 315! Throughout the first few weeks of the class, you will focus
on getting to know your client, fostering the start of a positive relationship,
and creating a mutual understanding of expectations for the report you will be
making for them.

In class, your UCA will provide you with your client's name, contact
information, and some details the client shared with us about their expectations
for the project. Please note, these details may be vague and that is okay. You
will be meeting with your client to ask additional questions and ensure you are
on the same page.

Your first step will be to send an introductory email to your client. Your email
should include a personal introduction and request to meet with your client. You
can also express your excitement to work on the project. Finally, you should
include a brief overview of what you want to discuss in the meeting, which is to
further clarify expectations and create a
[contract and timeline](../assignments/04-contract-timeline.qmd) for the project.

::: {.callout-important}
On this email, and **ALL** emails with your client going forward, you must CC
your UCA. This is very important throughout the semester so your UCA can monitor
your emails and help with any problems that may arise. Failing to CC your UCA on
email communications with your client could result in losing a professionalism
point.
:::

Please note that clients will know the project you are working on as the
**Community Link Project**, not PST 315. Most are aware that you are completing
this for class credit, but when referring to this project to your client, do not
refer to it as PST 315 -- just call it the Community Link Project.

When sending any emails to your client, please make sure to practice
professionalism. You want to foster a positive client relationship, and this
starts with presenting yourself professionally. A professional email should
include a concise subject, a salutation, straightforward and concise body
paragraphs, and a sign-off/signature. If you have any questions about this,
please talk to your UCA and they will be more than happy to help!

::: {.callout-tip title="Example introductory client email"}
**TO:** Your client's email (primary and secondary if you have one)
**FROM:** Your Syracuse email
**CC:** Your UCA's Syracuse email
**SUBJECT:** Community Link Project Introduction and Meeting

Dear Mr./Ms./Mrs. \_\_\_\_\_\_:

I hope this email finds you well. My name is Jordan Alvarez, and I have the
pleasure of being the student assigned to your Community Links Project for this
semester. I am very excited to work with you over the next few months to create
a meaningful report for your organization and learn more about what your goals
and achievements in the community are.

I was hoping we could meet in the next week or so to discuss more details about
your expectations for the report, as well as fill in a contract and timeline to
ensure your organization receives a report that is meaningful and timely. In the
proposal you filled out, you indicated that you are able to meet at the default
time on Monday, February 31st at 2:15 PM. However, if that has changed, I would
be more than happy to find another time that works better with your schedule.
Please just let me know and we can figure out the best time.

Thank you so much for trusting me with this Community Link Project and I look
forward to getting to know you throughout this semester. Please don't hesitate
to reach out with any questions.

Regards,
Jordan Alvarez
:::
