project:
  type: website
  output-dir: _site
  resources:
    - assignments/files/**
    - pst315_schedule.ics

website:
  title: "**PST 315**"
  site-url: https://jacklreilly.github.io/pst315_f26/
  repo-url: https://github.com/jacklreilly/pst315_f26
  navbar:
    background: "#1A5490"
    foreground: "#FFFFFF"
    right:
      - href: overview.qmd
        text: 🏠 Overview
      - href: logistics.qmd
        text: 📅 Logistics
      - href: assignments/index.qmd
        text: 📝 Assignments
      - href: guidelines/index.qmd
        text: 📗 Guidelines
      - href: policies.qmd
        text: 🏫 Policies
  page-footer:
    left: |
      © 2026 Jack Reilly<br>
      [Contact](mailto:jlreilly@syr.edu)

    right: |
      Built with [Quarto](https://quarto.org)<br>
      [About](/about.qmd)

  sidebar:
    - id: assign
      style: docked
      title: "Assignments"
      contents:
        - href: assignments/index.qmd
          text: "All Assignments"

        - section: "Getting Started"
          contents:
            - assignments/01-project-application.qmd
            - assignments/02-client-email.qmd
            - assignments/03-first-client-meeting.qmd
            - assignments/04-contract-timeline.qmd
            - assignments/05-second-client-meeting.qmd

        - section: "Project Organization"
          contents:
            - assignments/06-organizational-assessment.qmd
            - assignments/07-weekly-task-plan.qmd
            - assignments/08-draft-executive-summary.qmd
            - assignments/09-excel-coding-workshop.qmd
            - assignments/10-excel-graphing-workshop.qmd

        - section: "Practice Report"
          contents:
            - assignments/11-practice-report.qmd

        - section: "Report & Presentation"
          contents:
            - assignments/12-formatted-report-shell.qmd
            - assignments/13-rough-draft.qmd
            - assignments/14-final-report.qmd
            - assignments/15-final-presentation.qmd

        - section: "Wrap-Up"
          contents:
            - assignments/16-professional-materials.qmd
            - assignments/17-final-reflection.qmd

    - id: guides
      style: docked
      title: "Guidelines"
      contents:
        - href: guidelines/index.qmd
          text: "All Guidelines"

        - section: "Working With Your Client"
          contents:
            - guidelines/client-email.qmd
            - guidelines/initial-client-meeting.qmd
            - guidelines/contract-and-timeline.qmd
            - guidelines/second-client-meeting.qmd

        - section: "Working With Your Data"
          contents:
            - guidelines/codebook-and-spreadsheet.qmd
            - guidelines/qualitative-coding.qmd
            - guidelines/graphing.qmd

        - section: "Writing the Report"
          contents:
            - guidelines/executive-summary.qmd
            - guidelines/introduction-and-methods.qmd
            - guidelines/findings.qmd
            - guidelines/appendices.qmd
            - guidelines/footers-and-section-breaks.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
execute:
  freeze: auto
